import type { AssetRow } from "@/app/types/asset";

export const mockAssets: AssetRow[] = [
  {
    id: "1",
    name: "Dell Latitude 5540",
    category: "Computador",
    serialNumber: "DL-2024-001",
    acquisitionDate: "14/01/2024",
    status: "ATIVO",
  },
  {
    id: "2",
    name: 'Monitor LG 27"',
    category: "Monitor",
    serialNumber: "LG-2024-002",
    acquisitionDate: "19/02/2024",
    status: "ATIVO",
  },
  {
    id: "3",
    name: "Teclado Logitech MX Keys",
    category: "Periférico",
    serialNumber: "LG-2023-015",
    acquisitionDate: "09/06/2023",
    status: "ATIVO",
  },
  {
    id: "4",
    name: "Switch Cisco 24p",
    category: "Rede",
    serialNumber: "CS-2023-008",
    acquisitionDate: "04/03/2023",
    status: "MANUTENCAO",
  },
  {
    id: "5",
    name: "HP LaserJet Pro",
    category: "Impressora",
    serialNumber: "HP-2022-042",
    acquisitionDate: "21/11/2022",
    status: "INATIVO",
  },
  {
    id: "6",
    name: "Notebook Lenovo ThinkPad",
    category: "Computador",
    serialNumber: "LN-2024-010",
    acquisitionDate: "02/02/2024",
    status: "ATIVO",
  },
  {
    id: "7",
    name: "Monitor Dell P2419H",
    category: "Monitor",
    serialNumber: "DL-2023-120",
    acquisitionDate: "15/07/2023",
    status: "ATIVO",
  },
  {
    id: "8",
    name: "Mouse Logitech MX Master 3",
    category: "Periférico",
    serialNumber: "LG-2023-221",
    acquisitionDate: "01/08/2023",
    status: "ATIVO",
  },
  {
    id: "9",
    name: "Access Point Ubiquiti",
    category: "Rede",
    serialNumber: "UB-2023-034",
    acquisitionDate: "20/04/2023",
    status: "MANUTENCAO",
  },
  {
    id: "10",
    name: "Impressora Epson EcoTank",
    category: "Impressora",
    serialNumber: "EP-2022-098",
    acquisitionDate: "10/10/2022",
    status: "ATIVO",
  },
  {
    id: "11",
    name: "Desktop HP ProDesk",
    category: "Computador",
    serialNumber: "HP-2023-300",
    acquisitionDate: "05/05/2023",
    status: "ATIVO",
  },
  {
    id: "12",
    name: 'Monitor Samsung 24"',
    category: "Monitor",
    serialNumber: "SM-2023-144",
    acquisitionDate: "18/06/2023",
    status: "INATIVO",
  },
  {
    id: "13",
    name: "Headset HyperX Cloud",
    category: "Periférico",
    serialNumber: "HX-2024-011",
    acquisitionDate: "12/01/2024",
    status: "ATIVO",
  },
  {
    id: "14",
    name: "Roteador Mikrotik",
    category: "Rede",
    serialNumber: "MK-2022-210",
    acquisitionDate: "03/09/2022",
    status: "ATIVO",
  },
  {
    id: "15",
    name: "Brother DCP-L2540DW",
    category: "Impressora",
    serialNumber: "BR-2021-055",
    acquisitionDate: "28/11/2021",
    status: "MANUTENCAO",
  },
];
